In [3]:
item_list=['Bread','Milk','Eggs','Butter','Cocoa']
student_marks=[78,47,96,55,34]
hetero_list=[1,2,3,0,'text',True,3+2j]
print(item_list)
print(student_marks)
print(hetero_list)

['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
[78, 47, 96, 55, 34]
[1, 2, 3, 0, 'text', True, (3+2j)]


In [11]:
student_marks = [78,47,96,55,34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[83, 52, 101, 60, 39]


In [4]:
%%time
list1=list(range(1,1000000))
list1=list(range(1,1000001))
list=[]
for i in range(len(list)):
    list3.append(list1[i]+list2[i])


CPU times: total: 31.2 ms
Wall time: 51.6 ms


In [6]:
import numpy as np
student_marks_arr = np.array([78,47,96,55,34])
student_marks_arr

array([78, 47, 96, 55, 34])

In [10]:
car_attributes = [[18,15,18,61,17],[130,165,150,150,140],[307,350,318,304,3032]]
print(car_attributes)

[[18, 15, 18, 61, 17], [130, 165, 150, 150, 140], [307, 350, 318, 304, 3032]]


In [13]:
car_attributes_arr=np.array(car_attributes)
car_attributes_arr

array([[  18,   15,   18,   61,   17],
       [ 130,  165,  150,  150,  140],
       [ 307,  350,  318,  304, 3032]])

In [14]:
car_attributes_arr.shape

(3, 5)

In [15]:
car_attributes_arr.dtype

dtype('int32')

In [17]:
car_attributes = [[18,15,18,61,17],[130,165,150,150,140],[307,350,318,304,3032]]
car_attributes_arr=np.array(car_attributes,dtype='float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[  18.   15.   18.   61.   17.]
 [ 130.  165.  150.  150.  140.]
 [ 307.  350.  318.  304. 3032.]]
float64


In [18]:
cars=np.array(['chevrolet chevelle malibu','buick skylark 320','playmouth satellite','amc rebel sst','ford torino'])
cars[1]

'buick skylark 320'

In [19]:
car_names=['chevrolet chevelle malibu','buick skylark 320','playmouth satellite','amc rebel sst','ford torino']
horsepower=[130,165,150,150,140]
car_hp_arr=np.array([car_names,horsepower])
car_hp_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'playmouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [21]:
car_hp_arr[0]

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'playmouth satellite', 'amc rebel sst', 'ford torino'],
      dtype='<U25')

In [22]:
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U25')

In [23]:
car_hp_arr[0,1]

'buick skylark 320'

In [24]:
car_hp_arr[0,-2]

'amc rebel sst'

In [25]:
car=np.array(['chevrolet','buick','ply','amc','ford'])
cars[1:4]

array(['buick skylark 320', 'playmouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [29]:
car_names=['chevrolet','buick','ply','amc','ford']
horsepower=['130', '165', '150', '150', '140']
acceleration=[18,15,18,16,17]
car_hp_acc_arr=np.array([car_names,horsepower,acceleration])
car_hp_acc_arr


array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U11')

In [30]:
car_hp_acc_arr[0:3]

array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U11')

In [31]:
car_hp_acc_arr[0:2,3:5]

array([['amc', 'ford'],
       ['150', '140']], dtype='<U11')

In [32]:
car_hp_acc_arr[0:3,0:3]

array([['chevrolet', 'buick', 'ply'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U11')

In [35]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower=",np.mean(horsepower_arr))

Mean horsepower= 147.0


In [36]:
print("Minimum horsepower=",np.min(horsepower_arr))
print("Maximum horsepower=",np.max(horsepower_arr))

Minimum horsepower= 130
Maximum horsepower= 165


In [37]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print("Index of Minimum horsepower=",np.argmin(horsepower_arr))
print("Index of Maximum horsepower=",np.argmax(horsepower_arr))

Index of Minimum horsepower= 0
Index of Maximum horsepower= 1


In [40]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >=150)
print(x)
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [41]:
horsepower_arr[3]

150

In [45]:
horsepower_arr[[1,4]]

array([165, 140])

In [46]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
x = horsepower_arr > 135
print(x.dtype)
newarr = horsepower_arr[x]
print(x)
print(newarr)

bool
[False  True  True  True  True]
[165 150 150 140]


In [47]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print('original array :',horsepower_arr)
print('sorted array :',np.sort(horsepower_arr))
print('original array after sorting :',horsepower_arr)
Sortedarray = np.sort(horsepower_arr)
print(Sortedarray)

original array : [130 165 150 150 140]
sorted array : [130 140 150 150 165]
original array after sorting : [130 165 150 150 140]
[130 140 150 150 165]


In [48]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
np.sort(horsepower_arr)
print(horsepower_arr)
horsepower_arr.sort()
print(horsepower_arr)

[130 165 150 150 140]
[130 140 150 150 165]


In [49]:
horsepower=[130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print('original array :',horsepower_arr)
print('original array after sorting :',horsepower_arr)

original array : [130 165 150 150 140]
original array after sorting : [130 165 150 150 140]
